name: build-and-publish-docker-images

on:
  push:
    branches:
      - master

jobs:
  build-vtk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: publish-to-dockerhub
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: wyq977/vtk
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: vtk

  build-vtk_python:
    needs: [build-vtk]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: publish-to-dockerhub
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: wyq977/vtk_python
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: vtk_python

  build-lbibcell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: publish-to-dockerhub
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: wyq977/lbibcell
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: lbibcell
