name: lbibcell


on: 
  push:
    paths:
      - 'lbibcell/Dockerfile'

jobs:
  build_lbibcell:
    name: Build LBIBCell
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish LBIBCell
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wyq977/lbibcell
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: lbibcell/Dockerfile

