name: vtk

on: 
  push:
    paths:
      - 'vtk_python/Dockerfile'
      - 'vtk/Dockerfile'
      - '.github/workflows/vtk.yml'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish vtk
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wyq977/vtk
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: vtk/Dockerfile
    - name: Build and Publish vtk_python
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wyq977/vtk_python
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: vtk_python/Dockerfile
