name: Build and Publish vtk Docker

on: 
  push:
    paths:
      - 'vtk/Dockerfile'
      - '.github/workflows/vtk.yml'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wyq977/vtk
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: vtk/Dockerfile
