name: Build and Publish vtk_python Docker

on: 
  push:
    paths:
      - 'vtk_python/Dockerfile'
      - '.github/workflows/vtk_python.yml'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wyq977/vtk_python
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}